server:
  port: 8001
  servlet:
    context-path: /eduservice

spring:
  application:
    name: SERVICE-EDU
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: '0922'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  configuration:
    log-impl: # org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
